language: d

d: dmd

addons:
  postgresql: 9.4

services: postgresql

before_script:
  - psql -c 'create database "pgator-test";' -U postgres
  - psql --dbname="pgator-test" -f .travis-json_rpc.sql -U postgres

script:
  # compilation test for production
  - dub test
  #- dub build --build=release # disabled because strange linking bug in dmd 2.068.1
  - dub build --build=debug
  
  # testing client - final test suite
  - dub build --config=production --build=debug
  - dub build --config=testclient --build=debug
  - ./bin/pgator --config=".travis-pgator.conf" 2>&1 > /dev/null &
  - sleep 10
  - pgrep pgator > /tmp/pgator.pid
  - ./bin/pgator-client --conn="dbname=pgator-test user=postgres" --host="http://127.0.0.1:8080/"
  - kill %%
