dist: trusty

language: d

d:
  - dmd
  - dmd-beta
  - ldc
  - ldc-beta
  #- gdc disabled, waiting for std.experimental.logger

addons:
  postgresql: 9.4

  apt:
    packages:
        - libevent-dev
        - jq

services: postgresql

before_script:
  - psql -c 'create database "pgator-test"' -U postgres

script:
  - ./.test.sh .test_pgator.conf
