language: d

d:
  - dmd
  #- gdc is disabled, waiting for std.experimental.logger
  - ldc

addons:
  postgresql: 9.4

services: postgresql

before_script:
  - psql -c 'create database "pgator-test"' -U postgres

script:
  - ./.test.sh .test_pgator.conf
