language: d

d:
  - dmd
  - gdc
  - ldc

addons:
  postgresql: 9.4

services: postgresql

before_script:
  - psql -c 'create database "pgator-test";' -U postgres
  - psql --dbname="pgator-test" -f .travis-json_rpc.sql -U postgres

script:
  # compilation test for production
  - dub test
  - dub build --build=release
  - dub build --build=debug
  
  # testing client - final test suite
  - dub build --config=production --build=debug
  - dub build --config=testclient --build=debug
  - sudo ./bin/pgator --config=".travis-pgator.conf" --daemon
  - sudo ./bin/pgator-client --conn="dbname=pgator-test user=postgres" --host="http://127.0.0.1:8080/"
  - sudo kill -s SIGTERM $(pgrep pgator)
  - sudo cat ./pgator.log
