language: d

#compiler:
#  - dmd

services: PostgreSQL

before_script:
  - psql -c 'create database rpc-proxy-test;' -U postgres

install:
  # dmd
  # dub
  - DMD_VER=2.064.2
  - DMD=dmd_${DMD_VER}-0_amd64.deb
  - DUB_VER=0.9.20
  - DUB=dub-${DUB_VER}-linux-x86_64
  - wget http://downloads.dlang.org/releases/2013/${DMD}
  - sudo dpkg -i ${DMD} || true
  - sudo apt-get -y update
  - sudo apt-get -fy install
  - sudo dpkg -i ${DMD}
  - wget http://code.dlang.org/files/${DUB}.tar.gz
  - sudo tar -C /usr/local/bin -zxf ${DUB}.tar.gz

script:
  - dub build --config=test1 
  - ./bin/rpc-sql-proxy
  - dub build --config=test2 
  - ./bin/rpc-sql-proxy --conn="dbname=rpc-proxy-test user=postgres"
  # dub --config=unittest --build=unittest
  - dub --build=unittest