language: d

d:
  - dmd
  - dmd-2.066.1
  - gdc
  - ldc

addons:
  postgresql: 9.4

services: postgresql

before_script:
  - psql -c 'create database "pgator-test";' -U postgres
  - psql --dbname="pgator-test" -f .travis-json_rpc.sql -U postgres

script:
  # test-suite
  - dub build --config=test1 
  - ./pgator-backend-test1 --conn="dbname=pgator-test user=postgres"
  - dub build --config=test2 
  - ./pgator-backend-test2 --conn="dbname=pgator-test user=postgres"
  - dub test

  # compilation test for production
  - dub build --build=release
  - dub build --build=debug
