language: d

d:
  - dmd
  #- gdc disabled, waiting for std.experimental.logger
  #- ldc disabled, "logInfo: command not found"

addons:
  postgresql: 9.4

services: postgresql

before_script:
  - psql -c 'create database "pgator-test"' -U postgres

script:
  - ./.test.sh .test_pgator.conf
