language: d

addons:
  postgresql: 9.3

services: postgresql

before_script:
  - psql -c 'create database "pgator-test";' -U postgres
  - psql --dbname="pgator-test" -f .travis-json_rpc.sql -U postgres

install:
  # dmd
  # dub
  - DMD_VER=2.066.0
  - DMD=dmd_${DMD_VER}-0_amd64.deb
  - DUB_VER=0.9.21
  - DUB=dub-${DUB_VER}-linux-x86_64
  - wget http://downloads.dlang.org/releases/2014/${DMD}
  - sudo dpkg -i ${DMD} || true
  - sudo apt-get -y update
  - sudo apt-get -fy install
  - sudo dpkg -i ${DMD}
  - wget http://code.dlang.org/files/${DUB}.tar.gz
  - sudo tar -C /usr/local/bin -zxf ${DUB}.tar.gz

script:
  # compilation test for production
  - dub test
  - dub build --build=release
  - dub build --build=debug
  
  # testing client - final test suite
  - dub build --config=production --build=debug
  - dub build --config=testclient --build=debug
  - sudo ./bin/pgator --config=".travis-pgator.conf" --daemon
  - sudo ./bin/pgator-client --conn="dbname=pgator-test user=postgres" --host="http://127.0.0.1:8080"
  - sudo kill -s SIGTERM $(pgrep pgator)
