language: d

addons:
  postgresql: 9.3

services: postgresql

before_script:
  - psql -c 'create database "pgator-test";' -U postgres
  - psql --dbname="pgator-test" -f .travis-json_rpc.sql -U postgres

install:
  # dmd
  # dub
  - DMD_VER=2.066.0
  - DMD=dmd_${DMD_VER}-0_amd64.deb
  - DUB_VER=0.9.22
  - DUB=dub-${DUB_VER}-linux-x86_64
  - wget http://downloads.dlang.org/releases/2014/${DMD}
  - sudo dpkg -i ${DMD} || true
  - sudo apt-get -y update
  - sudo apt-get -fy install
  - sudo dpkg -i ${DMD}
  - wget http://code.dlang.org/files/${DUB}.tar.gz
  - sudo tar -C /usr/local/bin -zxf ${DUB}.tar.gz

script:
  # test-suite
  - dub build --config=test1 
  - ./pgator-backend-test1 --conn="dbname=pgator-test user=postgres"
  - dub build --config=test2 
  - ./pgator-backend-test2 --conn="dbname=pgator-test user=postgres"
  - dub test

  # compilation test for production
  - dub build --build=release
  - dub build --build=debug
