#!/bin/sh

set -e

service supervisor force-reload

if [ "$1" = "purge" ] ; then
        deluser --system pgator || true
        delgroup --system --only-if-empty pgator || true

        rm -r /var/log/pgator || true
fi

exit 0
